WineSitters/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('wine_recipes/', include('wine_recipes.urls')),
    path('users/', include('users.urls')),


    # index page
    path('', include('beer_recipes.urls')),

    # django pregenerated admin path
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

beer_recipes/urls.py
from django.urls import path

from beer_recipes import views


app_name = 'beer_recipes'

urlpatterns = [

    # /beer_recipes pattern, this one will be the final
    path('', views.index, name='index'),
    path('my_ingredients/', views.my_ingredients, name='my_ingredients'),  # Lists a users ingredients
    path('my_recipes/', views.my_recipes, name='my_recipes'),  # Lists a users recipes
    path('recipes/', views.recipes, name='recipes'),  # Lists all recipes
    path('ingredients/', views.ingredients, name='ingredients'),  # Lists all ingredients
    path('recipe_search/', views.search_recipes, name='search_recipes'),

    # All create url paths -------------------
    path('new_recipe/', views.new_recipe, name='new_recipe'),
    path('new_hop', views.new_hop, name='new_hop'),
    path('new_fermentable', views.new_fermentable, name='new_fermentable'),
    path('new_misc', views.new_misc, name='new_misc'),
    path('new_water', views.new_water, name='new_water'),
    path('new_yeast', views.new_yeast, name='new_yeast'),

    # All view url paths ----------------------
    path('view_recipe/<int:pk>', views.RecipeDetails.as_view(), name='RecipeDetails'),
    path('view_hop/<int:pk>', views.HopDetails.as_view(), name='HopDetails'),
    path('view_fermentable/<int:pk>', views.FermentableDetails.as_view(), name='FermentableDetails'),
    path('view_misc/<int:pk>', views.MiscDetails.as_view(), name='MiscDetails'),
    path('view_water/<int:pk>', views.WaterDetails.as_view(), name='WaterDetails'),
    path('view_yeast/<int:pk>', views.YeastDetails.as_view(), name='YeastDetails'),

    # All edit url paths -----------------------
    path('edit_recipe/<int:pk>', views.RecipeUpdate.as_view(), name='RecipeUpdate'),
    path('update_hop/<int:pk>', views.HopUpdate.as_view(), name='HopUpdate'),
    path('edit_fermentable/<int:pk>', views.FermentableUpdate.as_view(), name='FermentableUpdate'),
    path('edit_misc/<int:pk>', views.MiscUpdate.as_view(), name='MiscUpdate'),
    path('edit_water/<int:pk>', views.WaterUpdate.as_view(), name='WaterUpdate'),
    path('edit_yeast/<int:pk>', views.YeastUpdate.as_view(), name='YeastUpdate'),

    # All delete url paths ----------------------------------------------------
    path('delete_recipe/int<int:pk>', views.RecipeDelete.as_view(), name='RecipeDelete'),
    path('delete_hop/<int:pk>', views.HopDelete.as_view(), name='HopDelete'),
    path('delete_fermentable/<int:pk>', views.FermentableDelete.as_view(), name='FermentableDelete'),
    path('delete_misc/<int:pk>', views.MiscDelete.as_view(), name='MiscDelete'),
    path('delete_water/<int:pk>', views.WaterDelete.as_view(), name='WaterDelete'),
    path('delete_yeast/<int:pk>', views.YeastDelete.as_view(), name='YeastDelete'),

]

users/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'
urlpatterns = [
    # Auth urls
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='users/login.html')
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(template_name='users/logged_out.html')
    ),
    path('', include('django.contrib.auth.urls')),
    # Registration Page url
    path('register/', views.register, name='register'),
]

beer_recipes/forms.py
from django import forms
from beer_recipes.models import BeerRecipe, Hop, Fermentable, Yeast, Water, Misc


class RecipeForm(forms.ModelForm):
    # TODO: Add validation here
    class Meta:
        model = BeerRecipe
        fields = ['name', 'description', 'brewer',
                  'batch_size', 'boil_size', 'boil_time', 'type', 'image']


class HopForm(forms.ModelForm):
    # TODO: Add validation here
    class Meta:
        model = Hop
        exclude = ['version', 'date_submitted', 'user']


class FermentableForm(forms.ModelForm):
    # TODO: Add validation here
    class Meta:
        model = Fermentable
        exclude = ['version', 'date_submitted', 'user']


class YeastForm(forms.ModelForm):
    # TODO: Add validation here
    class Meta:
        model = Yeast
        exclude = ['version', 'date_submitted', 'user']


class MiscForm(forms.ModelForm):
    # TODO: Add validation here
    class Meta:
        model = Misc
        exclude = ['version', 'date_submitted', 'user']


class WaterForm(forms.ModelForm):
    # TODO: Add validation here
    class Meta:
        model = Water
        exclude = ['version', 'date_submitted', 'user']

beer_recipes/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic import DetailView
from django.urls import reverse_lazy
from beer_recipes.models import BeerRecipe, Hop, Fermentable, Yeast, Water, Misc
from beer_recipes.forms import RecipeForm, HopForm, FermentableForm, YeastForm, WaterForm, MiscForm

# Create your views here.


def index(request):
    """ Home Page for the beer_recipes app, may be temporary """
    return recipes(request)


#  List views here ------------------------------------------------------------
def recipes(request, error="", message=""):
    """ Displays all the recipes in a list """
    # Instantiate a dictionary of recipe objects
    recipes = BeerRecipe.objects.order_by('name')
    recipe_dict = {'recipes': recipes, 'error': error, 'message': message}

    return render(request, 'beer_recipes/recipe_list.html', recipe_dict)


# Eventually only admins should call this, don't know Jimmy's admin function
def ingredients(request, error="", message=""):
    """ Displays all the ingredients in a list """
    # Instantiate a dictionary of ingredients objects
    ingredients_dict = {'error': error, 'message': message}
    hops = Hop.objects.order_by('name')
    fermentables = Fermentable.objects.order_by('name')
    miscs = Misc.objects.order_by('name')
    waters = Water.objects.order_by('name')
    yeasts = Yeast.objects.order_by('name')
    ingredients_dict.update({'hops': hops, 'fermentables': fermentables,
                             'miscs': miscs, 'waters': waters, 'yeasts': yeasts})
    return render(request, 'beer_recipes/list_ingredients.html', ingredients_dict)


@login_required
def my_ingredients(request, error="", message=""):
    """ Displays all the users ingredients """
    ingredients_dict = {'error': error, 'message': message}

    current_user = request.user
    hops = Hop.objects.filter(user=current_user.username)
    fermentables = Fermentable.objects.filter(user=current_user.username)
    miscs = Misc.objects.filter(user=current_user.username)
    waters = Water.objects.filter(user=current_user.username)
    yeasts = Yeast.objects.filter(user=current_user.username)
    ingredients_dict.update({'hops': hops, 'fermentables': fermentables,
                             'miscs': miscs, 'waters': waters, 'yeasts': yeasts})
    return render(request, 'beer_recipes/list_ingredients.html', ingredients_dict)


@login_required
def my_recipes(request, error="", message=""):
    """ Displays all the users ingredients """
    recipes_dict = {'error': error, 'message': message}

    if request.method == 'GET':
        current_user = request.user
        recipes = BeerRecipe.objects.filter(user=current_user.username)
        recipes_dict.update({'recipes': recipes})

    return render(request, 'beer_recipes/recipe_list.html', recipes_dict)


def search_recipes(request, error="", message=""):
    """ Returns a list of recipes matching the search term (kinda) """
    recipes_dict = {'error': error, 'message': message}

    if request.method == 'POST':
        recipes = BeerRecipe.objects.filter(name__icontains = request.POST['search_term'])
        if recipes:  # Something was found
            temp_dict = {'recipes': recipes}
            recipes_dict.update(temp_dict)

        else:  # Nothing was found
            recipes_dict.update(error = 'Sorry, no recipes matched your search. Try again, or add a recipe now!')
    return render(request, 'beer_recipes/recipe_search.html', recipes_dict)


#  New views here -------------------------------------------------------------
@login_required
def new_recipe(request):
    """ Add a new recipe """
    if request.method != 'POST':
        form = RecipeForm()
    else:
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            new_recipe = form.save(commit=False)
            new_recipe.user = request.user.username
            new_recipe.save()
            return recipes(request, message="Successfully created recipe: " + request.POST['name'])

    context = {'form': form}
    # TODO: Start here tomorrow, create templates
    return render(request, 'beer_recipes/new_recipe.html', context)


@login_required
def new_hop(request):
    """ Creates a new hop """
    if request.method != 'POST':
        form = HopForm()
    else:
        form = HopForm(data=request.POST)
        if form.is_valid():
            new_hop = form.save(commit=False)
            new_hop.user = request.user.username
            new_hop.save()
            return my_ingredients(request, message="Successfully created hop: " + request.POST['name'])

    context = {'form': form}
    # TODO: Start here tomorrow, create templates
    return render(request, 'beer_recipes/new_hop.html', context)


@login_required
def new_fermentable(request):
    """ Creates a new fermentable """
    if request.method != 'POST':
        form = FermentableForm()
    else:
        form = FermentableForm(data=request.POST)
        if form.is_valid():
            new_ferm = form.save(commit=False)
            new_ferm.user = request.user.username
            new_ferm.save()
            return my_ingredients(request, message="Successfully created fermentable: " + request.POST['name'])

    context = {'form': form}
    # TODO: Start here tomorrow, create templates
    return render(request, 'beer_recipes/new_fermentable.html', context)


@login_required
def new_yeast(request):
    """ Creates a new yeast """
    if request.method != 'POST':
        form = YeastForm()
    else:
        form = YeastForm(data=request.POST)
        if form.is_valid():
            new_yeast = form.save(commit=False)
            new_yeast.user = request.user.username
            new_yeast.save()
            return my_ingredients(request, message="Successfully created yeast: " + request.POST['name'])

    context = {'form': form}
    # TODO: Start here tomorrow, create templates
    return render(request, 'beer_recipes/new_yeast.html', context)


@login_required
def new_misc(request):
    """ Creates a new miscellaneous ingredient """
    if request.method != 'POST':
        form = MiscForm()
    else:
        form = MiscForm(data=request.POST)
        if form.is_valid():
            new_misc = form.save(commit=False)
            new_misc.user = request.user.username
            new_misc.save()
            return my_ingredients(request, message="Successfully created miscellaneous ingredient: " + request.POST['name'])

    context = {'form': form}
    # TODO: Start here tomorrow, create templates
    return render(request, 'beer_recipes/new_misc.html', context)


@login_required
def new_water(request):
    """ Creates a new water profile """
    if request.method != 'POST':
        form = WaterForm()
    else:
        form = WaterForm(data=request.POST)
        if form.is_valid():
            new_water = form.save(commit=False)
            new_water.user = request.user.username
            new_water.save()
            return my_ingredients(request, message="Successfully created water profile: " + request.POST['name'])

    context = {'form': form}
    # TODO: Start here tomorrow, create templates
    return render(request, 'beer_recipes/new_water.html', context)


#  CRUD views here ------------------------------------------------------------
@login_required
def edit_recipe(request, error="", message=""):
    """ Edits information about a specific recipe """
    if request.method == 'GET':
        # create a temp object to store the get info
        temp = request.GET['edit_recipe']
        temp_recipe = BeerRecipe.objects.get(name=temp)
        return render(request, 'beer_recipes/edit_recipe.html', temp_recipe)


class HopUpdate(UpdateView):
    model = Hop
    fields = ['name', 'description', 'alpha', 'time', 'amount', 'use']
    success_url = reverse_lazy('beer_recipes:my_ingredients')


class HopDelete(DeleteView):
    model = Hop
    success_url = reverse_lazy('beer_recipes:my_ingredients')


class HopDetails(DetailView):
    model = Hop


class FermentableUpdate(UpdateView):
    model = Fermentable
    fields = ['name', 'description', 'amount', 'ferm_yield', 'color', 'type']
    success_url = reverse_lazy('beer_recipes:my_ingredients')


class FermentableDelete(DeleteView):
    model = Fermentable
    success_url = reverse_lazy('beer_recipes:my_ingredients')


class FermentableDetails(DetailView):
    model = Fermentable


class MiscUpdate(UpdateView):
    model = Misc
    fields = ['name', 'description']
    success_url = reverse_lazy('beer_recipes:my_ingredients')


class MiscDelete(DeleteView):
    model = Misc
    success_url = reverse_lazy('beer_recipes:my_ingredients')


class MiscDetails(DetailView):
    model = Misc


class WaterUpdate(UpdateView):
    model = Water
    fields = ['name', 'description']
    success_url = reverse_lazy('beer_recipes:my_ingredients')


class WaterDelete(DeleteView):
    model = Water
    success_url = reverse_lazy('beer_recipes:my_ingredients')


class WaterDetails(DetailView):
    model = Water


class YeastUpdate(UpdateView):
    model = Yeast
    fields = ['name', 'description']
    success_url = reverse_lazy('beer_recipes:my_ingredients')


class YeastDelete(DeleteView):
    model = Yeast


class YeastDetails(DetailView):
    model = Yeast


class RecipeDetails(DetailView):
    model = BeerRecipe


class RecipeUpdate(UpdateView):
    model = BeerRecipe
    fields = ['name', 'description', 'brewer',
              'batch_size', 'boil_size', 'boil_time', 'image', 'hops']
    success_url = reverse_lazy('beer_recipes:recipes')


class RecipeDelete(DeleteView):
    model = BeerRecipe
    success_url = reverse_lazy('beer_recipes:recipes')

templates/beer_recipes/base.html
{% load bootstrap4 %}
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, inital-scale-1,
    shrink-to-fit=no">

</head>

<body>
  <header>
    <div class="collapse bg-dark" id="navbarHeader">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-7 py-4">
            <h4 class="text-white">User Beer Recipes</h4>
            <p class="text-muted">Use the menu to the right to create or edit your ingredients.
              Then, use those ingredients to create recipes below.</p>
          </div>
          {% if user.is_authenticated %}
          <!-- Check if the user is logged in -->
          <div class="col-sm-4 offset-md-1 py-4">
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <h4 class="text-white">{{ user.username }}</h4>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">My Account</a>
                <a class="dropdown-item" href="#">Placeholder</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'users:logout' %}">Log Out</a>
              </div>
            </div>

            <ul class="list-unstyled">
              <li><a href="{% url 'beer_recipes:my_ingredients' %}" class="text-white">My Ingredients</a></li>
              <li><a href="{% url 'beer_recipes:my_recipes' %}" class="text-white">My Recipes</a></li>
              <li><a href="{% url 'beer_recipes:recipes' %}" class="text-white">All Recipes</a></li>
            </ul>
          </div>
          {% else %} <! -- User is not logged in -->
            <div class="col-sm-4 offset-md-1 py-4">
              <a href="{% url 'users:login' %}">
                <h4 class="text-white">Log In</h4>
              </a>
              <a href="{% url 'users:register' %}">
                <h4 class="text-white">Register</h4>
              </a>
            </div>
            {% endif %}
        </div>
      </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
      <div class="container d-flex justify-content-between">
        <a href="{% url 'beer_recipes:recipes' %}" class="navbar-brand d-flex align-items-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
            <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
            <circle cx="12" cy="13" r="4"></circle>
          </svg>
          <strong>Beer Recipes</strong>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>
  </header>

  <!-- The main content will be loaded in below -->
  <main role="main">
    <div id="main_content">
      {% block content %}{% endblock %}
    </div>
  </main>

  <footer class="text-muted">
    <div class="container">
      <p class="float-right">
        <a href="#">Back to top</a>
      </p>
      <p>This page is property of WineSitters BrewHouse &copy 2020</p>
      <a href="https://www.thewinesitters.com/"><address>
          WineSitter BrewHouse 2711 South Ave La Crosse, WI 54601
        </address></a>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
</body>

</html>

templates/beer_recipes/list_ingredients.html
{% extends 'beer_recipes/base.html' %}
{% load static %}
{% block content %}

<!-- Custom styles for this template -->
<link rel="stylesheet" href="{% static "css/beer_recipes/shared.css" %}" />

<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Ingredients</h1>
    <p class="lead">This is a collection of your submitted Ingredients. Add an Ingredient by clicking a button below.</p>
    <p>
      <a href="{% url 'beer_recipes:new_hop' %}" class="btn btn-secondary my-2">Create a New Hop</a>
      <a href="{% url 'beer_recipes:new_fermentable' %}" class="btn btn-secondary my-2">Create a New Fermentable Ingredient</a>
      <a href="{% url 'beer_recipes:new_misc' %}" class="btn btn-secondary my-2">Create a New Miscellaneous Ingredient</a>
      <a href="{% url 'beer_recipes:new_water' %}" class="btn btn-secondary my-2">Create a New Water Profile</a>
      <a href="{% url 'beer_recipes:new_yeast' %}" class="btn btn-secondary my-2">Create a New Yeast</a>
    </p>
  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container">

    {% if hops %}
    <!-- Check if there are any hops in the dict -->
    <h3>Hops:</h3>
    <div class="row">
      {% for hop in hops %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <div class="card-body">
            <h5 class="card-title">{{ hop.name }}</h5>
            <p class="card-text">{{ hop.description|truncatechars:125 }}...</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <!-- <form style="display: inline" action="{% url 'beer_recipes:HopDetails' hop.id %}"><button type="button" class="btn btn-sm btn-outline-secondary">View</button></a> -->

                <a href="{% url 'beer_recipes:HopDetails' hop.id %}" class="btn btn-sm btn-outline-secondary" role="button">View</a>
                <a href="{% url 'beer_recipes:HopUpdate' hop.id %}" class="btn btn-sm btn-outline-secondary" role="button">Edit</a>
                <a href="{% url 'beer_recipes:HopDelete' hop.id %}" class="btn btn-sm btn-outline-secondary" role="button">Delete</a>
              </div>
              <small class="text-muted">{{ hop.date_submitted }}</small>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}


    {% if fermentables %}
    <!-- Check if there are any fermentables in the dict -->
    <h3>Fermentables:</h3>
    <div class="row">
      {% for fermentable in fermentables %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <div class="card-body">
            <h5 class="card-title">{{ fermentable.name }}</h5>
            <p class="card-text">{{ fermentable.description|truncatechars:125 }}...</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{% url 'beer_recipes:FermentableDetails' fermentable.id %}" role="button" class="btn btn-sm btn-outline-secondary">View</a>
                <a href="{% url 'beer_recipes:FermentableUpdate' fermentable.id %}" role="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                <a href="{% url 'beer_recipes:FermentableDelete' fermentable.id %}" role="button" class="btn btn-sm btn-outline-secondary">Delete</a>
              </div>
              <small class="text-muted">{{ fermentable.date_submitted }}</small>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}

    {% if miscs %}
    <!-- Check if there are any miscs in the dict -->
    <h3>Miscellaneous Ingredients:</h3>
    <div class="row">
      {% for misc in miscs %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <div class="card-body">
            <h5 class="card-title">{{ misc.name }}</h5>
            <p class="card-text">{{ misc.description|truncatechars:125 }}...</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{% url 'beer_recipes:MiscDetails' misc.id %}" role="button" class="btn btn-sm btn-outline-secondary">View</a>
                <a href="{% url 'beer_recipes:MiscUpdate' misc.id %}" role="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                <a href="{% url 'beer_recipes:MiscDelete' misc.id %}" role="button" class="btn btn-sm btn-outline-secondary">Delete</a>
              </div>
              <small class="text-muted">{{ misc.date_submitted }}</small>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}

    {% if waters %}
    <!-- Check if there are any waters in the dict -->
    <h3>Water Profiles:</h3>
    <div class="row">
      {% for water in waters %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <div class="card-body">
            <h5 class="card-title">{{ water.name }}</h5>
            <p class="card-text">{{ water.description|truncatechars:125 }}...</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{% url 'beer_recipes:WaterDetails' water.id %}" role="button" class="btn btn-sm btn-outline-secondary">View</a>
                <a href="{% url 'beer_recipes:WaterUpdate' water.id %}" role="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                <a href="{% url 'beer_recipes:WaterDelete' water.id %}" role="button" class="btn btn-sm btn-outline-secondary">Delete</a>
              </div>
              <small class="text-muted">{{ water.date_submitted }}</small>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}

    {% if yeasts %}
    <!-- Check if there are any yeasts in the dict -->
    <h3>Yeasts:</h3>
    <div class="row">
      {% for yeast in yeasts %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <div class="card-body">
            <h5 class="card-title">{{ yeast.name }}</h5>
            <p class="card-text">{{ yeast.description|truncatechars:125 }}...</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{% url 'beer_recipes:YeastDetails' yeast.id %}" role="button" class="btn btn-sm btn-outline-secondary">View</a>
                <a href="{% url 'beer_recipes:YeastUpdate' yeast.id %}" role="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                <a href="{% url 'beer_recipes:YeastDelete' yeast.id %}" role="button" class="btn btn-sm btn-outline-secondary">Delete</a>
              </div>
              <small class="text-muted">{{ yeast.date_submitted }}</small>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}

    <!-- Check if there are no ingredients at all -->
    {% if not hops and not fermentables and not miscs and not waters and not yeasts %}
      <h3>It appears that you have no ingredients created yet. Create one by choosing a button above.</h3>
    {% endif %}
  </div>
</div>

{% endblock content %}

templates/beer_recipes/recipe_search.html
{% extends 'beer_recipes/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static "css/beer_recipes/shared.css" %}" />

<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Recipe Search</h1>
    <p class="lead">Search for a recipe. Results are shown below.</p>
    <p>
      <form class="form-inline mt-2 mt-md-0" action="{% url 'beer_recipes:search_recipes' %}" method='post'> {% csrf_token %}
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name='search_term'>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit" value="submit" id="submit">Search</button>
      </form>
    </p>
  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container">
    {% if error %}
      <h4 style="color:red;">{{ error }}</h4>
    {% endif %}
    <div class="row">
      {% if recipes %}
      <!-- Check if there are any recipes in the dict -->
      {% for recipe in recipes %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          {% if not recipe.image %}
          <img class="card-img-top" src="{% static "pictures/shared/no_picture.svg" %}" alt="Card image cap">
          {% else %}
          <img class="card-img-top" src="{{ recipe.image.url }}" alt="Card image cap">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ recipe.name }}</h5>
            <p class="card-text">{{ recipe.description|truncatechars:125 }}...</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{% url 'beer_recipes:RecipeDetails' recipe.id %}" class="btn btn-sm btn-outline-secondary" role="botton">View</a>
                {% if recipe.user == user.username %}
                  <a href="{% url 'beer_recipes:RecipeUpdate' recipe.id %}" class="btn btn-sm btn-outline-secondary" role="botton">Edit</a>
                  <a href="{% url 'beer_recipes:RecipeDelete' recipe.id %}" class="btn btn-sm btn-outline-secondary" role="botton">Delete</a>
                {% endif %}
              </div>
              <small class="text-muted">{{ recipe.date_submitted }}</small>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      <!-- {% else %} <!-- There are no recipes in the dict -->
        <!-- <h4 id="no_recipes">Sorry, no recipes matched your search. Try again, or add a recipe now!</h4> -->
      {% endif %}

{% endblock content %}