WineSitters/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('wine_recipes/', include('wine_recipes.urls')),
    path('users/', include('users.urls')),


    # index page
    path('', include('beer_recipes.urls')),

    # django pregenerated admin path
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

beer_recipes/urls.py
from django.urls import path

from beer_recipes import views


app_name = 'beer_recipes'

urlpatterns = [

    # /beer_recipes pattern, this one will be the final
    path('', views.index, name='index'),
    path('my_ingredients/', views.my_ingredients, name='my_ingredients'),  # Lists a users ingredients
    path('my_recipes/', views.my_recipes, name='my_recipes'),  # Lists a users recipes
    path('recipes/', views.recipes, name='recipes'),  # Lists all recipes
    path('ingredients/', views.ingredients, name='ingredients'),  # Lists all ingredients
    path('recipe_search/', views.search_recipes, name='search_recipes'),

    # All create url paths -------------------
    path('new_recipe/', views.new_recipe, name='new_recipe'),
    path('new_hop', views.new_hop, name='new_hop'),
    path('new_fermentable', views.new_fermentable, name='new_fermentable'),
    path('new_misc', views.new_misc, name='new_misc'),
    path('new_water', views.new_water, name='new_water'),
    path('new_yeast', views.new_yeast, name='new_yeast'),

    # All view url paths ----------------------
    path('view_recipe/<int:pk>', views.RecipeDetails.as_view(), name='RecipeDetails'),
    path('view_hop/<int:pk>', views.HopDetails.as_view(), name='HopDetails'),
    path('view_fermentable/<int:pk>', views.FermentableDetails.as_view(), name='FermentableDetails'),
    path('view_misc/<int:pk>', views.MiscDetails.as_view(), name='MiscDetails'),
    path('view_water/<int:pk>', views.WaterDetails.as_view(), name='WaterDetails'),
    path('view_yeast/<int:pk>', views.YeastDetails.as_view(), name='YeastDetails'),

    # All edit url paths -----------------------
    path('edit_recipe/<int:pk>', views.RecipeUpdate.as_view(), name='RecipeUpdate'),
    path('update_hop/<int:pk>', views.HopUpdate.as_view(), name='HopUpdate'),
    path('edit_fermentable/<int:pk>', views.FermentableUpdate.as_view(), name='FermentableUpdate'),
    path('edit_misc/<int:pk>', views.MiscUpdate.as_view(), name='MiscUpdate'),
    path('edit_water/<int:pk>', views.WaterUpdate.as_view(), name='WaterUpdate'),
    path('edit_yeast/<int:pk>', views.YeastUpdate.as_view(), name='YeastUpdate'),

    # All delete url paths ----------------------------------------------------
    path('delete_recipe/int<int:pk>', views.RecipeDelete.as_view(), name='RecipeDelete'),
    path('delete_hop/<int:pk>', views.HopDelete.as_view(), name='HopDelete'),
    path('delete_fermentable/<int:pk>', views.FermentableDelete.as_view(), name='FermentableDelete'),
    path('delete_misc/<int:pk>', views.MiscDelete.as_view(), name='MiscDelete'),
    path('delete_water/<int:pk>', views.WaterDelete.as_view(), name='WaterDelete'),
    path('delete_yeast/<int:pk>', views.YeastDelete.as_view(), name='YeastDelete'),

]

users/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'
urlpatterns = [
    # Auth urls
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='users/login.html')
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(template_name='users/logged_out.html')
    ),
    path('', include('django.contrib.auth.urls')),
    # Registration Page url
    path('register/', views.register, name='register'),
]

wine_recipes/urls.py
from django.urls import path

from wine_recipes import views

app_name = 'wine_recipes'

urlpatterns = [
    # Index pattern
    path('', views.index, name='index'),

    #/wine_recipes patterns, this one will be the final
    path('', views.index, name='index'),
    path('my_ingredients/', views.my_ingredients,
         name='my_ingredients'),  # Lists a users ingredients
    path('my_recipes/', views.my_recipes, name='my_recipes'),  # Lists a users recipes
    path('recipes/', views.recipes, name='recipes'),  # Lists all recipes
    path('landing_page/', views.land, name='land'),
    # path('ingredients/', views.ingredients,
    #      name='ingredients'),  # Lists all ingredients
    # path('recipe_search/', views.search_recipes, name='search_recipes'),
    #
    # # All create url paths --
    # -----------------
    # path('new_recipe/', views.new_recipe, name='new_recipe'),
    # path('new_hop', views.new_hop, name='new_hop'),
    # path('new_fermentable', views.new_fermentable, name='new_fermentable'),
    # path('new_misc', views.new_misc, name='new_misc'),
    # path('new_water', views.new_water, name='new_water'),
    # path('new_yeast', views.new_yeast, name='new_yeast'),
    #
    # # All view url paths ----------------------
    # path('view_recipe/<int:pk>', views.RecipeDetails.as_view(), name='RecipeDetails'),
    # path('view_hop/<int:pk>', views.HopDetails.as_view(), name='HopDetails'),
    # path('view_fermentable/<int:pk>', views.FermentableDetails.as_view(), name='FermentableDetails'),
    # path('view_misc/<int:pk>', views.MiscDetails.as_view(), name='MiscDetails'),
    # path('view_water/<int:pk>', views.WaterDetails.as_view(), name='WaterDetails'),
    # path('view_yeast/<int:pk>', views.YeastDetails.as_view(), name='YeastDetails'),
    #
    # # All edit url paths -----------------------
    # path('edit_recipe/<int:pk>', views.RecipeUpdate.as_view(), name='RecipeUpdate'),
    # path('update_hop/<int:pk>', views.HopUpdate.as_view(), name='HopUpdate'),
    # path('edit_fermentable/<int:pk>', views.FermentableUpdate.as_view(), name='FermentableUpdate'),
    # path('edit_misc/<int:pk>', views.MiscUpdate.as_view(), name='MiscUpdate'),
    # path('edit_water/<int:pk>', views.WaterUpdate.as_view(), name='WaterUpdate'),
    # path('edit_yeast/<int:pk>', views.YeastUpdate.as_view(), name='YeastUpdate'),
    #
    # # All delete url paths ----------------------------------------------------
    # path('delete_recipe/int<int:pk>', views.RecipeDelete.as_view(), name='RecipeDelete'),
    # path('delete_hop/<int:pk>', views.HopDelete.as_view(), name='HopDelete'),
    # path('delete_fermentable/<int:pk>', views.FermentableDelete.as_view(), name='FermentableDelete'),
    # path('delete_misc/<int:pk>', views.MiscDelete.as_view(), name='MiscDelete'),
    # path('delete_water/<int:pk>', views.WaterDelete.as_view(), name='WaterDelete'),
    # path('delete_yeast/<int:pk>', views.YeastDelete.as_view(), name='YeastDelete'),

]

wine_recipes/models.py
from django.db import models
from datetime import date
from django import forms

# Create your models here.


class WineRecipe(models.Model):
    """ This is a recipe that a user creates """

    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(blank=True)
    date_submitted = models.DateField(auto_now_add=True)
    version = models.PositiveIntegerField(default=1)

wine_recipes/forms.py
from django import forms
from wine_recipes.models import WineRecipe

class RecipeForm(forms.ModelForm):
        """ This is the form for the creation of a new recipe """
        model = WineRecipe
        

wine_recipes/views.py
from django.shortcuts import render, redirect
from wine_recipes.models import WineRecipe
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    """ Home Page for the wine_recipes app, may be temporary """
    return render(request, 'wine_recipes/index.html')

def land(request):
    return render(request,'wine_recipes/landing_page.html')

def recipes(request, message="", error=""):
    """ Displays all the recipes in a list """
    # Instantiate a dictionary of recipe objects
    recipes = WineRecipe.objects.order_by('name')
    recipe_dict = {'recipes': recipes}

    return render(request, 'wine_recipes/recipe_search.html', recipe_dict)


def view_recipe(request):
    """ Displays information about a specific recipe """
    if request.method == 'GET':
        # create a temp object to store the get info
        temp = request.GET['view_recipe']
        temp_recipe = WineRecipe.objects.get(name__startswith=temp)
        return render(request, 'wine_recipes/view_recipe.html', temp_recipe)


@login_required
def my_ingredients(request):
    return redirect('wine_recipes:index')


@login_required
def my_recipes(request):
    return redirect('wine_recipes:index')


@login_required
def new_recipe(request):
    """ Add a new recipe """
    if request.method != 'POST':
        # form = RecipeForm()
        return redirect('wine_recipes:index')
    else:
        return redirect('wine_recipes:index')

        # form = RecipeForm(data=request.POST)
        # if form.is_valid():
        #     form.save()
        #     return recipes(request, message="Successfully created recipe:" + request.POST['recipe_name'])

    return redirect('wine_recipes:index')

templates/wine_recipes/base.html
{% load bootstrap4 %}
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, inital-scale-1,
    shrink-to-fit=no">

</head>

<body>
  <header>
    <div class="collapse bg-dark" id="navbarHeader">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-7 py-4">
            <h4 class="text-white">User Wine Recipes</h4>
            <p class="text-muted">Use the menu to the right to create or edit your ingredients.
              Then, use those ingredients to create recipes below.</p>
              <a href="{% url 'beer_recipes:index %'}" ><h4 class="text-white">User Beer Recipes</h4></a>
              <p class="text-muted">We also have a great selection of beer recipes for you to try.</p>
          </div>
          {% if user.is_authenticated %}
          <!-- Check if the user is logged in -->
          <div class="col-sm-4 offset-md-1 py-4">
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <h4 class="text-white">{{ user.username }}</h4>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">My Account</a>
                <a class="dropdown-item" href="#">Placeholder</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'users:logout' %}">Log Out</a>
              </div>
            </div>

            <ul class="list-unstyled">
              <li><a href="{% url 'wine_recipes:my_ingredients' %}" class="text-white">My Ingredients</a></li>
              <li><a href="{% url 'wine_recipes:my_recipes' %}" class="text-white">My Recipes</a></li>
              <li><a href="{% url 'wine_recipes:recipes' %}" class="text-white">All Recipes</a></li>
            </ul>
          </div>
          {% else %} <! -- User is not logged in -->
            <div class="col-sm-4 offset-md-1 py-4">
              <a href="{% url 'users:login' %}">
                <h4 class="text-white">Log In</h4>
              </a>
              <a href="{% url 'users:register' %}">
                <h4 class="text-white">Register</h4>
              </a>
            </div>
            {% endif %}
        </div>
      </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
      <div class="container d-flex justify-content-between">
        <a href="{% url 'wine_recipes:recipes' %}" class="navbar-brand d-flex align-items-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
            <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
            <circle cx="12" cy="13" r="4"></circle>
          </svg>
          <strong>Wine Recipes</strong>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>
  </header>

  <!-- The main content will be loaded in below -->
  <main role="main">
    <div id="main_content">
      {% block content %}{% endblock %}
    </div>
  </main>

  <footer class="text-muted">
    <div class="container">
      <p class="float-right">
        <a href="#">Back to top</a>
      </p>
      <p>This page is property of WineSitters BrewHouse &copy 2020</p>
      <a href="https://www.thewinesitters.com/"><address>
          WineSitter BrewHouse 2711 South Ave La Crosse, WI 54601
        </address></a>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
</body>

</html>

templates/wine_recipes/hop_confirm_delete.html
{% extends 'beer_recipes/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!-- Custom styles for this template -->
<link rel="stylesheet" href="{% static "css/beer_recipes/shared.css" %}" />

<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Delete Hop</h1>
    <p class="lead">Please confirm below.</p>
  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container">
    <form method='post' name='delete_hop'>
      {% csrf_token %}
      Are you sure you would like to delete this hop?
      <button type="submit" class="btn btn-danger">Delete Hop</button>
    </form>
  </div>
</div>
{% endblock content %}

templates/wine_recipes/hop_detail.html
{% extends 'beer_recipes/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!-- Custom styles for this template -->
<link rel="stylesheet" href="{% static "css/beer_recipes/shared.css" %}" />

<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Hop Details</h1>
  </div>
</section>
<div class="album py-5 bg-light">
  <div class="container">
    <p>Name: {{ object.name }}</p>
    <p>Date added: {{ object.date_submitted|date }}</p>
    <p>Hop Version: {{ object.version }}</p>
    <p>Amount in Kg: {{ object.amount }}</p>
    <p>Alpha: {{ object.alpha }}%</p>
    <p>Use: {{ object.use }}</p>
    {% if object.use == "Mash" %}
      <p>Mash Time: {{ object.time }}</p>
    {% elif object.use == "Boil" or object.use == "First Wort" %}
      <p>Boil Time: {{ object.time }}</p>
    {% elif object.use == "Aroma" %}
      <p>Steep Time: {{ object.time }}</p>
    {% elif object.use == "Dry Hop" %}
      <p>Dry Hop Time: {{ object.time }}</p>
    {% endif %}
    {% if object.description %}
      <p>Description: {{ object.description }}</p>
    {% endif %}
  </div>
</div>
{% endblock content %}

templates/wine_recipes/hop_form.html
{% extends 'beer_recipes/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Edit Hop</h1>
    <p class="lead">Edit the hop by filling out the form below.</p>
  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container">
    <form method='post' name='edit_hop'>
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-success">Edit Hop</button>
    </form>
  </div>
</div>
{% endblock content %}

templates/wine_recipes/index.html
{% extends "shared/base.html" %}

{% block content %}
  <!-- <p>
  </p> -->
{% endblock content %}

templates/wine_recipes/landing_page.html
{% extends 'wine_recipes/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<!-- Custom styles for this template -->
<link rel="stylesheet" href="{% static "css/wine_recipes/shared.css" %}" />

<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Coming Soon!</h1>
    <p class="lead">This feature is coming shortly. Check back soon!</p>
  </div>
</section>


{% endblock content %}

templates/wine_recipes/recipe_search.html
{% extends 'shared/base.html' %}
{% load static %}

{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static "css/wine_search.css" %}"/>

  <div class="banner-photo">
    <img src="{% static "pictures/wine_banner.png" %}" width="100%" height="602">
    <br><br>
  </div>

  <div class="container">
    <div class="jumbotron">
      <h1>Wine Recipes</h1>
      <div id="Search Bar">
      	<input type="text" name"TitleSearch" id="Search Bar"/>
      	<button>Search</button>
    	</div>
      <div id="recipe_table">
        {% if recipes %} <!-- Check if there are any recipes in the dict -->
          <table>
            <thead>
              <th>Recipe Name</th>
              <th>Description</th>
              <th>Submission Date</th>
            </thead>
            {% for recipe in recipes %}
              <form action="{% url 'wine_recipes:view_recipe' %}" id="{{ recipe.name }}" method="get" name="{{ recipe.name }}">
                <tr>
                  <td>{{ recipe.name }}</td>
                  <td>{{ recipe.description }}</td>
                  <td>{{ recipe.date_submitted }}</td>
                  <td class="view_recipe_button_cell">
                    <button name="view_recipe" value="{{ recipe.name }}" form="{{ recipe.name }}" class="btn btn-primary" id="{{ recipe.name }}" onclick="this.form.submit();">View Recipe</button>
                  </td>
                </tr>
              </form>
            {% endfor %}
          </table>
        {% else %} <!-- There are no recipes in the dict -->
          <h4 id="no_recipes">Sorry, no recipes matched your search. Try again, or add a recipe now!</h4>
        {% endif %}
      </div>
      <a href="{% url 'wine_recipes:new_recipe' %}">Add a new Recipe</a>
    </div>
  </div>

{% endblock content %}