WineSitters/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('wine_recipes/', include('wine_recipes.urls')),
    path('users/', include('users.urls')),


    # index page
    path('', include('beer_recipes.urls')),

    # django pregenerated admin path
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

beer_recipes/urls.py
from django.urls import path

from beer_recipes import views


app_name = 'beer_recipes'

urlpatterns = [

    # /beer_recipes pattern, this one will be the final
    path('', views.index, name='index'),
    path('my_ingredients/', views.my_ingredients, name='my_ingredients'),  # Lists a users ingredients
    path('my_recipes/', views.my_recipes, name='my_recipes'),  # Lists a users recipes
    path('recipes/', views.recipes, name='recipes'),  # Lists all recipes
    path('ingredients/', views.ingredients, name='ingredients'),  # Lists all ingredients
    path('recipe_search/', views.search_recipes, name='search_recipes'),

    # All create url paths -------------------
    path('new_recipe/', views.new_recipe, name='new_recipe'),
    path('new_hop', views.new_hop, name='new_hop'),
    path('new_fermentable', views.new_fermentable, name='new_fermentable'),
    path('new_misc', views.new_misc, name='new_misc'),
    path('new_water', views.new_water, name='new_water'),
    path('new_yeast', views.new_yeast, name='new_yeast'),

    # All view url paths ----------------------
    path('view_recipe/<int:pk>', views.RecipeDetails.as_view(), name='RecipeDetails'),
    path('view_hop/<int:pk>', views.HopDetails.as_view(), name='HopDetails'),
    path('view_fermentable/<int:pk>', views.FermentableDetails.as_view(), name='FermentableDetails'),
    path('view_misc/<int:pk>', views.MiscDetails.as_view(), name='MiscDetails'),
    path('view_water/<int:pk>', views.WaterDetails.as_view(), name='WaterDetails'),
    path('view_yeast/<int:pk>', views.YeastDetails.as_view(), name='YeastDetails'),

    # All edit url paths -----------------------
    path('edit_recipe/<int:pk>', views.RecipeUpdate.as_view(), name='RecipeUpdate'),
    path('update_hop/<int:pk>', views.HopUpdate.as_view(), name='HopUpdate'),
    path('edit_fermentable/<int:pk>', views.FermentableUpdate.as_view(), name='FermentableUpdate'),
    path('edit_misc/<int:pk>', views.MiscUpdate.as_view(), name='MiscUpdate'),
    path('edit_water/<int:pk>', views.WaterUpdate.as_view(), name='WaterUpdate'),
    path('edit_yeast/<int:pk>', views.YeastUpdate.as_view(), name='YeastUpdate'),

    # All delete url paths ----------------------------------------------------
    path('delete_recipe/int<int:pk>', views.RecipeDelete.as_view(), name='RecipeDelete'),
    path('delete_hop/<int:pk>', views.HopDelete.as_view(), name='HopDelete'),
    path('delete_fermentable/<int:pk>', views.FermentableDelete.as_view(), name='FermentableDelete'),
    path('delete_misc/<int:pk>', views.MiscDelete.as_view(), name='MiscDelete'),
    path('delete_water/<int:pk>', views.WaterDelete.as_view(), name='WaterDelete'),
    path('delete_yeast/<int:pk>', views.YeastDelete.as_view(), name='YeastDelete'),

]

users/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'
urlpatterns = [
    # Auth urls
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='users/login.html')
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(template_name='users/logged_out.html')
    ),
    path('', include('django.contrib.auth.urls')),
    # Registration Page url
    path('register/', views.register, name='register'),
]

wine_recipes/urls.py
from django.urls import path

from wine_recipes import views

app_name = 'wine_recipes'

urlpatterns = [
    # Index pattern
    path('', views.index, name='index'),

    #/wine_recipes patterns, this one will be the final
    path('', views.index, name='index'),
    path('my_ingredients/', views.my_ingredients,
         name='my_ingredients'),  # Lists a users ingredients
    path('my_recipes/', views.my_recipes, name='my_recipes'),  # Lists a users recipes
    path('recipes/', views.recipes, name='recipes'),  # Lists all recipes
    path('landing_page/', views.land, name='land'),
    # path('ingredients/', views.ingredients,
    #      name='ingredients'),  # Lists all ingredients
    # path('recipe_search/', views.search_recipes, name='search_recipes'),
    #
    # # All create url paths --
    # -----------------
    # path('new_recipe/', views.new_recipe, name='new_recipe'),
    # path('new_hop', views.new_hop, name='new_hop'),
    # path('new_fermentable', views.new_fermentable, name='new_fermentable'),
    # path('new_misc', views.new_misc, name='new_misc'),
    # path('new_water', views.new_water, name='new_water'),
    # path('new_yeast', views.new_yeast, name='new_yeast'),
    #
    # # All view url paths ----------------------
    # path('view_recipe/<int:pk>', views.RecipeDetails.as_view(), name='RecipeDetails'),
    # path('view_hop/<int:pk>', views.HopDetails.as_view(), name='HopDetails'),
    # path('view_fermentable/<int:pk>', views.FermentableDetails.as_view(), name='FermentableDetails'),
    # path('view_misc/<int:pk>', views.MiscDetails.as_view(), name='MiscDetails'),
    # path('view_water/<int:pk>', views.WaterDetails.as_view(), name='WaterDetails'),
    # path('view_yeast/<int:pk>', views.YeastDetails.as_view(), name='YeastDetails'),
    #
    # # All edit url paths -----------------------
    # path('edit_recipe/<int:pk>', views.RecipeUpdate.as_view(), name='RecipeUpdate'),
    # path('update_hop/<int:pk>', views.HopUpdate.as_view(), name='HopUpdate'),
    # path('edit_fermentable/<int:pk>', views.FermentableUpdate.as_view(), name='FermentableUpdate'),
    # path('edit_misc/<int:pk>', views.MiscUpdate.as_view(), name='MiscUpdate'),
    # path('edit_water/<int:pk>', views.WaterUpdate.as_view(), name='WaterUpdate'),
    # path('edit_yeast/<int:pk>', views.YeastUpdate.as_view(), name='YeastUpdate'),
    #
    # # All delete url paths ----------------------------------------------------
    # path('delete_recipe/int<int:pk>', views.RecipeDelete.as_view(), name='RecipeDelete'),
    # path('delete_hop/<int:pk>', views.HopDelete.as_view(), name='HopDelete'),
    # path('delete_fermentable/<int:pk>', views.FermentableDelete.as_view(), name='FermentableDelete'),
    # path('delete_misc/<int:pk>', views.MiscDelete.as_view(), name='MiscDelete'),
    # path('delete_water/<int:pk>', views.WaterDelete.as_view(), name='WaterDelete'),
    # path('delete_yeast/<int:pk>', views.YeastDelete.as_view(), name='YeastDelete'),

]

templates/shared/base.html
{% load bootstrap4 %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, inital-scale-1,
    shrink-to-fit=no">

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
</head>
<body>
  <nav class= "navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'wine_recipes:index' %}">Plumbus Labs</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarCollapse" aria-controls="navbarCollapse"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'wine_recipes:wine_recipes' %}">
            Wine Recipes</a></li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'beer_recipes:index' %}">
            Beer Recipes</a></li>
      </ul>

      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text}">Hello, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>
</body>

</html>